      - name: 🧱 Puppeteer için sistem kütüphanelerini kur (Ubuntu 24.04 uyumlu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxss1 \
            libxshmfence1 \
            libpango-1.0-0 \
            libcairo2 \
            libxkbcommon0 \
            libasound2t64 \
            lsb-release \
            fonts-liberation \
            libfontconfig1 \
            xdg-utils \
            wget
