name: Run B2B Scraper and Update Product Data

on:
  schedule:
    # Her gün UTC 00:00'da çalışır (Türkiye saatiyle 03:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # Manuel tetikleme için

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Push izni

    steps:
      - name: 📥 Repo'yu klonla
        uses: actions/checkout@v4

      - name: 🟢 Node.js kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Puppeteer için ideal sürüm

      - name: 🧱 Puppeteer için sistem kütüphanelerini kur
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2-data \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxss1 \
            libxshmfence1 \
            libpango-1.0-0 \
            libcairo2 \
            libxkbcommon0 \
            lsb-release \
            fonts-liberation \
            libfontconfig1 \
            xdg-utils \
            wget

      - name: 📦 NPM bağımlılıklarını yükle
        run: npm install puppeteer fs-extra dotenv

      - name: 🚀 Scraper script'ini çalıştır
        env:
          DERMO_EMAIL: ${{ secrets.DERMO_EMAIL }}
          DERMO_PASSWORD: ${{ secrets.DERMO_PASSWORD }}
          ANIMAL_EMAIL: ${{ secrets.ANIMAL_EMAIL }}
          ANIMAL_PASSWORD: ${{ secrets.ANIMAL_PASSWORD }}
        run: node b2b_scraper.js

      - name: 💾 JSON verilerini commit & push et (varsa)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add urunler/api/products.json urunler/api/hayvan-sagligi.json
          if git diff --staged --quiet; then
            echo "📦 Değişiklik yok, commit atılmadı."
          else
            git commit -m "Scraper: Update product data in urunler/api"
            git push
          fi
